version: "2"

# .golangci.yml

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosec

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadow
  gosec:
    excludes:
      - G104 # Duplicates errcheck
      - G304 # File path from variable (expected in CLI)

issues:
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

run:
  timeout: 5m
  tests: true
