version: 2

project_name: threads

before:
  hooks:
    - go mod tidy

builds:
  # macOS builds with CGO for keychain support
  - id: threads-darwin
    binary: threads
    main: ./cmd/threads
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X github.com/salmonumbrella/threads-cli/internal/cmd.Version={{.Version}}
      - -X github.com/salmonumbrella/threads-cli/internal/cmd.Commit={{.ShortCommit}}
      - -X github.com/salmonumbrella/threads-cli/internal/cmd.BuildDate={{.Date}}

  # Linux/Windows builds without CGO
  - id: threads-other
    binary: threads
    main: ./cmd/threads
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/salmonumbrella/threads-cli/internal/cmd.Version={{.Version}}
      - -X github.com/salmonumbrella/threads-cli/internal/cmd.Commit={{.ShortCommit}}
      - -X github.com/salmonumbrella/threads-cli/internal/cmd.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: salmonumbrella
    name: threads-cli
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
